tag_types={"2014 review":"theme",
"acid":"concept",
"algorithms":"theme",
"altiscale":"company",
"architecture":"theme",
"archival":"theme",
"avro":"project",
"benchmarks":"theme",
"big data architecture":"theme",
"bloomberg":"company",
"bluedata":"company",
"calcite":"project",
"camus":"project",
"cap":"concept",
"case-study":"theme",
"cassandra":"project",
"cerner":"company",
"cloudera":"company",
"configuration":"theme",
"confluent":"company",
"coprocessors":"concept",
"cost-based optimizers":"concept",
"data ingestion":"theme",
"data lake":"concept",
"data pipelines":"concept",
"data protection":"theme",
"data science":"theme",
"data warehousing":"theme",
"databricks":"company",
"dataflow":"project",
"dataframes":"concept",
"db":"theme",
"decision trees":"concept",
"deep learning":"concept",
"design":"theme",
"distributed ml":"theme",
"ebay":"company",
"emr":"project",
"encryption":"theme",
"ensemble decision tree":"concept",
"etsy":"company",
"f1":"project",
"falcon":"project",
"fault tolerance":"theme",
"feature engineering":"theme",
"forex trading":"theme",
"foundationdb":"project",
"google":"company",
"graphflow":"project",
"h20":"company",
"hadoop":"project",
"haversine":"concept",
"hbase":"project",
"hdfs":"project",
"high availability":"theme",
"hive":"project",
"hortonworks":"company",
"hpc":"theme",
"impala":"project",
"inmobi":"company",
"intel":"company",
"ipython notebooks":"project",
"jkreps":"person",
"kafka":"project",
"lambda architecture":"concept",
"lens":"project",
"life":"theme",
"linkedin":"company",
"luigi":"project",
"machine learning":"theme",
"mapreduce":"project",
"memsql":"project",
"mesos":"project",
"mirroring":"theme",
"myriad":"project",
"nifi":"project",
"open source":"theme",
"operability":"theme",
"optimization":"theme",
"pandas":"project",
"parquet":"project",
"parsely":"project",
"paypal":"company",
"performance monitoring":"theme",
"pinterest":"company",
"pnuts":"project",
"programming":"theme",
"pulsar":"project",
"r-language":"project",
"ranger":"project",
"scheduling":"theme",
"security":"theme",
"sentry":"project",
"shell scripting":"theme",
"shuffle":"concept",
"slider":"project",
"spark":"project",
"spark sql":"project",
"spark streaming":"project",
"sparkml":"project",
"spotify":"company",
"storm":"project",
"stream processing":"theme",
"tachyon":"project",
"teaching":"theme",
"tez":"project",
"tiered storage":"theme",
"time-series":"theme",
"troubleshooting":"theme",
"twitter":"company",
"yahoo":"company",
"yarn":"project",
"zookeeper":"project",
"exactly once": "concept",
"mysql": "project",
"datasets": "theme",
"startup": "company",
"ensemble decision trees": "concept",
"solr": "project",
"pagerank": "concept",
"logs": "concept",
"distributed coordination": "concept",
"metamarkets": "company",
"sql": "theme",
"groovy": "theme",
"kixer": "company",
"riffle": "project",
"atscale": "company",
"postgres": "project",
"s3": "project",
"mongodb": "project",
"aws": "project",
"presto": "project",
"adnear": "company",
"data catalog": "concept",
"socialite": "project",
"strace": "project",
"bigbench": "project",
"crunch": "project",
"ambari": "project",
"druid": "project",
"lily hbase indexer": "project",
"adtech": "theme",
"log structured merge": "concept",
"climate": "theme",
"cloud": "theme",
"qubole": "company",
"s3-journal": "project",
"rocksdb": "project",
"metadata": "theme",
"disque": "project",
"factual": "company",
"cascading": "project",
"nasdaq": "company",
"distributed messaging": "concept",
"getindata": "company",
"consistency": "concept",
"sstable": "concept",
"edmunds.com": "company",
"memory": "theme",
"cask": "project",
"concurrent users": "concept",
"db-as-a-libray": "concept",
"stonebraker": "person",
"elastic search": "project",
"file formats": "theme",
"roadmap": "theme",
"mdm": "concept",
"data prep": "theme",
"anamoly detection": "concept",
"medical science": "theme",
"amazon": "company",
"groupon": "company",
"csv": "theme",
"distributed operating sys": "theme",
"orc": "theme",
"gobblin": "project",
"enhanced networking": "theme",
"pearson": "company",
"morphlines": "project",
"etl": "theme",
"alation": "company",
"logstash": "project",
"elk": "theme",
"datapad": "project",
"samza": "project",
"rule-engine": "theme",
"jepsen": "project",
"leveldb": "project",
"micro-batching": "concept",
"redis": "project",
"production": "theme",
"atlas": "project",
"splice machine": "project",
"object storage": "concept",
"topic modelling": "concept",
"metrics": "theme",
"monitoring": "theme",
"python": "theme",
"sort": "concept",
"eharmony": "company",
"lda": "concept",
"java 8": "theme",
"multi-armed bandit": "concept",
"comparison": "theme",
"pig": "project",
"netflix": "company"}
